# Generated by Django 3.0.7 on 2020-06-11 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200610_1956'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetAcquireRequest',
            fields=[
                ('assetrequest_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.AssetRequest')),
                ('requested_asset_detail', models.TextField()),
            ],
            bases=('app.assetrequest',),
        ),
        migrations.RemoveField(
            model_name='assetrequest',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='assetrequest',
            name='requested_asset',
        ),
        migrations.CreateModel(
            name='AssetAccessRequest',
            fields=[
                ('assetrequest_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.AssetRequest')),
                ('requested_asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Asset')),
            ],
            bases=('app.assetrequest',),
        ),
    ]
