# Generated by Django 3.0.7 on 2020-06-08 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_delete_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='address',
        ),
        migrations.AddField(
            model_name='location',
            name='room_number',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
